stages:
  - deploy

deployment:
  image:
    name: docker/compose:1.24.1
    entrypoint: ["/bin/sh", "-c"]
  stage: deploy
  script:
    - docker-compose build
    - BOT_TOKEN=$BOT_TOKEN FIRE_PRIVATE_KEY_ID=$FIRE_PRIVATE_KEY_ID FIRE_PRIVATE_KEY=$FIRE_PRIVATE_KEY FIRE_CLIENT_EMAIL=$FIRE_CLIENT_EMAIL FIRE_CLIENT_ID=$FIRE_CLIENT_ID FIRE_CLIENT_CERT_URL=$FIRE_CLIENT_CERT_URL docker-compose up -d
  only:
    - master
