stages:
  - deploy

deployment:
  image:
    name: docker/compose:1.24.1
    entrypoint: ["/bin/sh", "-c"]
  stage: deploy
  script:
    - docker-compose build
    - BOT_TOKEN=$BOT_TOKEN docker-compose up -d
  only:
    - master
